name: hourly-taxi-demand-feature-pipeline

on:
  schedule:
    - cron: '0 * * * *'


jobs:

  feature_pipeline:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.10.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'
          
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: execute python workflows from bash script
      env: 
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      
      run: |
        export PYTHONPATH="${PYTHONPATH}:../"
        jupyter nbconvert --to notebook --execute notebooks/12_feature_pipeline.ipynb

